 # Site settings

title: Ana Ragazzi Portfolio
description: Graphic Designer // Illustrator // Web Designer
email: ana.sragazzi@gmail.com


#Build settings
markdown: kramdown
permalink: pretty

port: 7000

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested